import { NAV_ITEMS, seedData, START_DATE } from './data.js';

const KEY='careeros-state-v1';
const clone=x=>JSON.parse(JSON.stringify(x));
let state=load();
let route=location.hash.replace('#/','')||'command';
const esc=(v='')=>String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const uid=p=>p+Math.random().toString(36).slice(2,9);
function load(){try{return JSON.parse(localStorage.getItem(KEY))||clone(seedData)}catch{return clone(seedData)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function fmt(s){return s?new Date(s+'T12:00:00').toLocaleDateString('en-CA',{month:'short',day:'numeric'}):'—'}
function rank(s){return ['Saved','Applied','Contacted','Recruiter Screen','Assessment','Technical Interview','Hiring Manager','Final Interview','Reference Check','Offer'].indexOf(s)}
function badge(s){const c=['Offer','Opportunity','Credibility'].includes(s)?'good':['Rejected','Ghosted'].includes(s)?'bad':['Final Interview','Technical Interview','Hiring Manager'].includes(s)?'warn':'';return `<span class="badge ${c}">${esc(s)}</span>`}
function progress(v){return `<div class="progress"><i style="width:${Math.min(100,Math.max(0,v))}%"></i></div>`}
function head(k,t,s,a=''){return `<div class="page-head"><div><div class="eyebrow">${k}</div><h2>${t}</h2><p class="sub">${s}</p></div>${a}</div>`}
function metrics(){const apps=state.applications.filter(x=>x.status!=='Saved').length;return{apps,targeted:state.applications.filter(x=>x.tier<=2&&x.status!=='Saved').length,screens:state.applications.filter(x=>rank(x.status)>=3&&rank(x.status)<=9).length,tech:state.applications.filter(x=>rank(x.status)>=5&&rank(x.status)<=9).length,finals:state.applications.filter(x=>rank(x.status)>=7&&rank(x.status)<=9).length,offers:state.applications.filter(x=>x.status==='Offer').length,referrals:state.applications.filter(x=>x.referral).length,active:state.applications.filter(x=>!['Rejected','Ghosted','Offer'].includes(x.status)).length}}
function balance(){const m=metrics(),p=state.projects[0]?.score||0;return{Proof:p,Reach:Math.min(100,Math.round(m.apps/state.targets.applications*100)),Relationships:Math.min(100,Math.round(state.contacts.length/state.targets.connections*100)),Readiness:Math.min(100,Math.round(state.codingProblems.filter(x=>x.solved).length/state.targets.coding*100))}}
function phase(){const start=new Date(START_DATE+'T00:00:00'),now=new Date('2026-08-31T12:00:00'),d=Math.max(1,Math.floor((now-start)/86400000)+1);return{day:d,week:Math.ceil(d/7),name:d<=30?'Market Entry + Credibility':d<=60?'Interview Pipeline':'Offer Conversion'}}
function shell(){return `<div class="shell"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark">C</div><div><h1>CareerOS</h1><small>JOB ACQUISITION SYSTEM</small></div></div><nav>${NAV_ITEMS.map(([id,l,i])=>`<button data-route="${id}" class="${route===id?'active':''}"><span>${i}</span>${l}</button>`).join('')}</nav><div class="sidebar-foot">${state.meta.demo?'Demo data active':'Live workspace'}</div></aside><main><header class="topbar"><button class="icon mobile" id="menu">☰</button><button class="search" id="search">⌕ Search CareerOS… <kbd>⌘ K</kbd></button><div><button class="icon" id="theme">◐</button><button class="btn primary" id="add">＋ Add</button></div></header><div class="content" id="page"></div></main></div>`}
function command(){const m=metrics(),b=balance(),p=phase(),avg=Math.round(Object.values(b).reduce((a,c)=>a+c,0)/4);const cards=[['Applications',m.apps,state.targets.applications],['Targeted',m.targeted,state.targets.targeted],['Active pipeline',m.active,20],['Recruiter screens',m.screens,5],['Interviews',state.interviews.length,3],['Referrals',m.referrals,state.targets.referrals],['Contacts',state.contacts.length,state.targets.connections],['Follow-ups',state.contacts.filter(x=>x.next).length,state.targets.followups]].map(x=>`<div class="card metric"><span>${x[0]}</span><strong>${x[1]}</strong><small>Target ${x[2]}</small>${progress(x[1]/x[2]*100)}</div>`).join('');const tasks=state.tasks.filter(x=>!x.done).sort((a,b)=>b.priority-a.priority).slice(0,5).map((t,i)=>`<div class="task"><button data-task="${t.id}" class="check">✓</button><div><strong>${i+1}. ${esc(t.title)}</strong><small>${esc(t.category)} · priority ${t.priority}</small></div></div>`).join('');return `${head('Mission control','Command Center','One operating view for proof, reach, relationships, readiness, and conversion.')}<section class="card hero"><div><div class="eyebrow">DAY ${p.day} · WEEK ${p.week}</div><h2>${p.name}</h2><p class="sub">Keep all four acquisition systems moving.</p></div><div class="score">${avg}%</div></section><div class="grid four">${cards}</div><section class="card"><h3>Weekly operating balance</h3><div class="balance">${Object.entries(b).map(([k,v])=>`<div><header><span>${k}</span><strong>${v}%</strong></header>${progress(v)}</div>`).join('')}</div></section><div class="grid two"><section class="card"><h3>Today's priority queue</h3>${tasks||'<p class="sub">Queue cleared.</p>'}</section><section class="card"><h3>Upcoming interviews</h3>${state.interviews.map(i=>`<div class="line"><strong>${esc(i.company)} · ${esc(i.stage)}</strong><small>${new Date(i.date).toLocaleString('en-CA',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></div>`).join('')}</section></div>`}
function today(){return `${head('Daily execution','Today','Turn the weekly strategy into concrete work.',`<button class="btn primary" data-add="task">＋ Task</button>`)}<div class="grid two"><section class="card"><h3>Priority checklist</h3>${state.tasks.map(t=>`<div class="task"><button class="check ${t.done?'done':''}" data-task="${t.id}">✓</button><div><strong>${esc(t.title)}</strong><small>${esc(t.category)} · ${fmt(t.due)}</small></div></div>`).join('')}</section><section class="card"><h3>Time blocks</h3>${state.timeBlocks.map(b=>`<div class="line"><strong>${b.time} — ${esc(b.title)}</strong><small>${esc(b.category)} · ${b.duration} min</small></div>`).join('')}</section></div>`}
function applications(){return `${head('Distribution','Applications','Track every opportunity from discovery to offer.',`<button class="btn primary" data-add="job">＋ Application</button>`)}<section class="card table-wrap"><table><thead><tr><th>Company / Role</th><th>Status</th><th>Tier</th><th>Location</th><th>Match</th><th>Resume</th><th>Follow-up</th></tr></thead><tbody>${state.applications.map(a=>`<tr><td><strong>${esc(a.company)}</strong><small>${esc(a.position)}</small></td><td>${badge(a.status)}</td><td>T${a.tier}</td><td>${esc(a.location)} · ${esc(a.work)}</td><td>${a.match}%</td><td>${esc(a.resume)}</td><td>${fmt(a.followup)}</td></tr>`).join('')}</tbody></table></section>`}
function companies(){return `${head('Market intelligence','Companies','Build and prioritize your target-company universe.',`<button class="btn primary" data-add="company">＋ Company</button>`)}<div class="grid three">${state.companies.map(c=>`<section class="card"><div class="title"><h3>${esc(c.name)}</h3><span class="badge">Tier ${c.tier}</span></div><p class="sub">${esc(c.industry)} · ${esc(c.location)}</p><p>${esc(c.why)}</p><div class="pills">${c.stack.split(',').map(x=>`<span class="badge">${esc(x.trim())}</span>`).join('')}</div><small>Relationship strength ${'●'.repeat(c.strength)}${'○'.repeat(5-c.strength)}</small></section>`).join('')}</div>`}
function network(){const stages=['Recognition','Conversation','Familiarity','Credibility','Opportunity'];return `${head('Relationships','Network / CRM','Move people from recognition toward opportunity.',`<button class="btn primary" data-add="contact">＋ Contact</button>`)}<div class="grid three">${state.contacts.map(c=>`<section class="card"><div class="title"><h3>${esc(c.name)}</h3>${badge(c.type)}</div><p class="sub">${esc(c.role)} · ${esc(c.company)}</p><div class="ladder">${stages.map((s,i)=>`<i class="${i<=stages.indexOf(c.stage)?'on':''}"></i>`).join('')}</div><p>${esc(c.notes||'No notes yet.')}</p><small>Next follow-up ${fmt(c.next)} ${c.referral?'· Referral path':''}</small></section>`).join('')}</div>`}
function interviews(){return `${head('Conversion','Interviews','Prepare, debrief, and improve conversion.',`<button class="btn primary" data-add="interview">＋ Interview</button>`)}<div class="grid two">${state.interviews.map(i=>`<section class="card"><div class="title"><h3>${esc(i.company)}</h3>${badge(i.stage)}</div><p class="sub">${esc(i.job)} · ${esc(i.format)}</p><p><strong>Topics:</strong> ${esc(i.topics)}</p><div class="note">Prep: ${esc(i.prep)}</div></section>`).join('')}</div><section class="card table-wrap"><h3>Interview failure log</h3><table><thead><tr><th>Company</th><th>Question</th><th>Category</th><th>Quality</th><th>Missing concept</th><th>Retest</th></tr></thead><tbody>${state.failures.map(f=>`<tr><td>${esc(f.company)}</td><td>${esc(f.question)}</td><td>${badge(f.category)}</td><td>${f.quality}%</td><td>${esc(f.missing)}</td><td>${fmt(f.retest)}</td></tr>`).join('')}</tbody></table></section>`}
function preparation(){return `${head('Readiness','Preparation','Build competence against the interviews you are actually getting.')}<div class="grid three">${state.preparation.map(p=>`<section class="card"><div class="title"><h3>${esc(p.topic)}</h3><strong>${p.readiness}%</strong></div>${progress(p.readiness)}<small>Confidence ${p.confidence}% · next ${fmt(p.next)}</small></section>`).join('')}</div><section class="card table-wrap"><h3>Coding / SQL problems</h3><table><thead><tr><th>Problem</th><th>Pattern</th><th>Difficulty</th><th>Quality</th><th>Revisit</th></tr></thead><tbody>${state.codingProblems.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.category)}</td><td>${badge(p.difficulty)}</td><td>${p.quality}%</td><td>${fmt(p.revisit)}</td></tr>`).join('')}</tbody></table></section>`}
function projects(){const p=state.projects[0];return `${head('Proof','Projects / Proof','Make your engineering evidence recruiter-ready.')}<section class="card hero"><div><div class="eyebrow">FLAGSHIP PROJECT</div><h2>${esc(p.name)}</h2><p class="sub">${esc(p.subtitle)}</p></div><div class="score">${p.score}%</div></section><div class="grid two"><section class="card"><h3>Recruiter readiness</h3>${Object.entries(p.categories).map(([k,v])=>`<div class="score-row"><span>${esc(k)}</span>${progress(v)}<strong>${v}%</strong></div>`).join('')}</section><section class="card"><h3>Milestones</h3>${p.milestones.map(m=>`<div class="task"><button class="check ${m.done?'done':''}" data-mile="${m.id}">✓</button><strong>${esc(m.title)}</strong></div>`).join('')}</section></div>`}
function scorecard(){const m=metrics(),rows=[['Applications',m.apps,'applications'],['Targeted applications',m.targeted,'targeted'],['Contacts',state.contacts.length,'connections'],['Follow-ups',state.contacts.filter(x=>x.next).length,'followups'],['Coding / SQL',state.codingProblems.length,'coding'],['Project milestones',state.projects[0].milestones.filter(x=>x.done).length,'milestones']];return `${head('Operating cadence','Weekly Scorecard','Measure enough activity to generate meaningful market feedback.')}<section class="card">${rows.map(([l,v,k])=>`<div class="score-row"><span>${l}</span>${progress(v/state.targets[k]*100)}<strong>${v}/${state.targets[k]}</strong></div>`).join('')}</section>`}
function analytics(){const m=metrics(),screen=m.apps?Math.round(m.screens/m.apps*100):0,tech=m.screens?Math.round(m.tech/m.screens*100):0,final=m.tech?Math.round(m.finals/m.tech*100):0;let diag='Keep collecting data. Your current sample is too small for a major strategic diagnosis.';if(m.apps>=100&&m.screens<3)diag='Top-of-funnel problem detected: audit positioning, resume, targeting, geography, referrals and job freshness.';else if(m.screens>=5&&m.tech<2)diag='Screening conversion problem detected: tighten story, project explanation, motivation and fundamentals.';else if(m.tech>=5&&m.finals<2)diag='Technical interview bottleneck detected: increase Python, SQL, debugging, backend and project-depth practice.';return `${head('Decision intelligence','Analytics','Use conversion data to change the right system—not everything at once.')}<div class="grid four"><div class="card metric"><span>App → screen</span><strong>${screen}%</strong></div><div class="card metric"><span>Screen → technical</span><strong>${tech}%</strong></div><div class="card metric"><span>Technical → final</span><strong>${final}%</strong></div><div class="card metric"><span>Offers</span><strong>${m.offers}</strong></div></div><section class="card"><h3>Diagnostic engine</h3><div class="note">${diag}</div></section>`}
function roadmap(){return `${head('90-day system','30/60/90 Roadmap','Progress from market entry to interview pipeline to offer conversion.')}<div class="roadmap">${[['Days 1–30','Market Entry + Credibility','~100 applications · positioning · network · flagship progress'],['Days 31–60','Interview Pipeline','deployed flagship · demo · tests/CI · referrals · mocks'],['Days 61–90','Offer Conversion','interviews · targeted applications · closing weaknesses']].map((x,i)=>`<section class="card"><span class="badge">Phase ${i+1}</span><h3>${x[0]} — ${x[1]}</h3><p class="sub">${x[2]}</p></section>`).join('')}</div>`}
function activity(){return `${head('System history','Activity','A unified timeline of work and opportunity movement.')}<section class="card">${state.activity.map(a=>`<div class="line"><strong>${esc(a.text)}</strong><small>${esc(a.type)} · ${new Date(a.time).toLocaleString('en-CA',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</small></div>`).join('')}</section>`}
function settings(){return `${head('Configuration','Settings','Tune CareerOS to your operating model.')}<div class="grid two"><section class="card"><h3>Workspace</h3><div class="setting"><span>Theme</span><button class="btn" id="theme2">${state.meta.theme}</button></div><div class="setting"><span>Career hours/week</span><input class="input small" id="hours" type="number" value="${state.meta.weeklyHours}"></div></section><section class="card"><h3>Data</h3><p class="sub">This version persists in this browser via localStorage.</p><button class="btn" id="reset">Reset demo data</button></section></div>`}
function page(){return({command,today,applications,companies,network,interviews,preparation,projects,scorecard,analytics,roadmap,activity,settings}[route]||command)()}
function addActivity(type,text){state.activity.unshift({id:uid('a'),time:new Date().toISOString(),type,text})}
function modal(title,body,saveFn){const w=document.createElement('div');w.className='modal-bg';w.innerHTML=`<div class="modal"><div class="title"><h3>${title}</h3><button class="icon close">×</button></div><form>${body}<div class="modal-actions"><button type="button" class="btn close">Cancel</button><button class="btn primary">Save</button></div></form></div>`;document.body.appendChild(w);w.querySelectorAll('.close').forEach(x=>x.onclick=()=>w.remove());w.querySelector('form').onsubmit=e=>{e.preventDefault();saveFn(new FormData(e.currentTarget));save();w.remove();render()}}
const f=(n,l,t='text')=>`<label>${l}<input class="input" name="${n}" type="${t}" required></label>`;
function openAdd(type){if(type==='task')modal('Add task',`${f('title','Task')}<label>Category<select class="input" name="category"><option>Proof</option><option>Reach</option><option>Relationships</option><option>Readiness</option></select></label>${f('due','Due','date')}`,d=>{state.tasks.push({id:uid('t'),title:d.get('title'),category:d.get('category'),due:d.get('due'),priority:70,done:false,link:''});addActivity('Task',`Created task: ${d.get('title')}`)});else if(type==='company')modal('Add company',`${f('name','Company')}${f('industry','Industry')}${f('location','Location')}`,d=>{state.companies.unshift({id:uid('c'),name:d.get('name'),tier:2,industry:d.get('industry'),location:d.get('location'),size:'Unknown',policy:'Hybrid',stack:'',why:'',last:'2026-08-31',next:'',strength:1})});else if(type==='contact')modal('Add contact',`${f('name','Name')}${f('company','Company')}${f('role','Role')}`,d=>{state.contacts.unshift({id:uid('n'),name:d.get('name'),company:d.get('company'),role:d.get('role'),type:'Engineer',stage:'Recognition',last:'2026-08-31',next:'',referral:false,notes:''})});else if(type==='interview')modal('Add interview',`${f('company','Company')}${f('job','Job')}${f('date','Date & time','datetime-local')}`,d=>{state.interviews.push({id:uid('i'),company:d.get('company'),job:d.get('job'),stage:'Recruiter Screen',date:d.get('date'),format:'Video',interviewer:'TBD',topics:'',prep:'',outcome:'Pending'})});else modal('Add application',`${f('company','Company')}${f('position','Position')}${f('location','Location')}${f('match','Match %','number')}`,d=>{state.applications.unshift({id:uid('j'),company:d.get('company'),position:d.get('position'),location:d.get('location'),work:'Hybrid',tier:2,source:'Manual',date:'2026-08-31',status:'Saved',resume:'Backend',match:+d.get('match'),referral:false,next:'',followup:'',salary:'',stack:'',notes:''});addActivity('Application',`Added ${d.get('position')} at ${d.get('company')}`)})}
function search(){const w=document.createElement('div');w.className='palette';w.innerHTML='<input class="input" placeholder="Search jobs, companies, contacts…" autofocus><div id="results"></div>';document.body.appendChild(w);const all=[...state.applications.map(x=>`${x.company} — ${x.position}`),...state.companies.map(x=>x.name),...state.contacts.map(x=>`${x.name} — ${x.company}`)];const draw=q=>w.querySelector('#results').innerHTML=all.filter(x=>x.toLowerCase().includes(q.toLowerCase())).slice(0,12).map(x=>`<div class="result">${esc(x)}</div>`).join('')||'<p class="sub">No results</p>';draw('');w.querySelector('input').oninput=e=>draw(e.target.value);setTimeout(()=>w.querySelector('input').focus(),10);const close=e=>{if(e.key==='Escape'){w.remove();removeEventListener('keydown',close)}};addEventListener('keydown',close)}
function render(){document.documentElement.dataset.theme=state.meta.theme||'dark';document.getElementById('app').innerHTML=shell();document.getElementById('page').innerHTML=page();bind()}
function bind(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{route=b.dataset.route;location.hash='#/'+route;render()});document.querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>{const t=state.tasks.find(x=>x.id===b.dataset.task);t.done=!t.done;save();render()});document.querySelectorAll('[data-mile]').forEach(b=>b.onclick=()=>{const m=state.projects[0].milestones.find(x=>x.id===b.dataset.mile);m.done=!m.done;state.projects[0].score=Math.round(state.projects[0].milestones.filter(x=>x.done).length/state.projects[0].milestones.length*100);save();render()});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openAdd(b.dataset.add));document.getElementById('add').onclick=()=>openAdd(route==='applications'?'job':route==='companies'?'company':route==='network'?'contact':route==='interviews'?'interview':'task');document.getElementById('theme').onclick=()=>{state.meta.theme=state.meta.theme==='dark'?'light':'dark';save();render()};document.getElementById('search').onclick=search;document.getElementById('menu').onclick=()=>document.getElementById('sidebar').classList.toggle('open');const t=document.getElementById('theme2');if(t)t.onclick=()=>{state.meta.theme=state.meta.theme==='dark'?'light':'dark';save();render()};const h=document.getElementById('hours');if(h)h.onchange=e=>{state.meta.weeklyHours=+e.target.value;save()};const r=document.getElementById('reset');if(r)r.onclick=()=>{if(confirm('Reset to demo data?')){state=clone(seedData);save();render()}}}
addEventListener('hashchange',()=>{route=location.hash.replace('#/','')||'command';render()});addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search()}});render();
